### ISSUE TITLE
Hiển thị category trong product

### ISSUE THREAD

**Issue by giangnguyen93** [copvang/doc-mix-html#1]
![2](https://cloud.githubusercontent.com/assets/23069401/20623345/c2c9f760-b339-11e6-857b-91e5a4ce522f.PNG)

**Comment by vuongminh** [comment]
Fixed thank @giangnguyen93

**Comment by dtmanh** [comment]
![c2c9f760-b339-11e6-857b-91e5a4ce522f](https://cloud.githubusercontent.com/assets/13465226/20637895/2a0b16fa-b3c8-11e6-9d66-51a2d57e400d.PNG)
Thẻ Breadcrumb sẽ giải quyết vấn đề này !
